name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
           image: oyinlola101/frontend
           tags: v1
           addLatest: true
           registry: docker.io
           dockerfile: frontend.txt
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
           image: oyinlola101/backend
           tags: v1
           addLatest: true
           registry: docker.io
           dockerfile: backend.txt
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
           image: oyinlola101/simple-chat-app
           tags: v1
           addLatest: true
           registry: docker.io
           dockerfile: simple-chat-app/dockerfile
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
